# Configuration file to generate test-ui-ui via kickoff
# kickoff -a test-ui.yml -f ~/topics/react-redux-ui-archetype/ -d test-ui
package_name: test-ui
package_description: The implementation of the React UI of the test-ui application
author_full_name: Test Author
author_email: testauthor@gmail.com
author_github_account: testauthor
ui_store_module_name: test-ui-store
ui_store_module_version: 1.0.0
port: 3001
urlPrefix: /rest
apiVersion: 1.0.0
